<a href="https://colab.research.google.com/github/a01739368-glitch/tc1002s_semana_tec/blob/main/Actividad_1_2_A01739368.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
arreglo = np.full(10,5)
print (arreglo)

[5 5 5 5 5 5 5 5 5 5]


In [8]:
arreglo2 = np.arange(10,51,2)
print (arreglo2)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [13]:
random = np.random.randint(0, 101, (4, 4))
print (random)

[[ 7 11 88 99]
 [ 7 27 77 21]
 [99 52 83 43]
 [79 86 11 25]]


In [16]:
random = np.random.rand(10)
sum = np.sum(random)
print (random)
print ("Suma de randoms", sum)

[0.22567535 0.32796467 0.46318079 0.73875342 0.89782744 0.16571684
 0.52446174 0.85731038 0.29720762 0.72457452]
Suma de randoms 5.222672754938117


In [17]:
random = np.random.rand(10)
mean = np.mean(random)
print (random)
print ("mean de randoms", mean)

[0.43555079 0.0422067  0.35665563 0.10037091 0.71639041 0.55107582
 0.15761401 0.32626798 0.68854078 0.31942659]
mean de randoms 0.3694099616967399


In [19]:
import pandas as pd

df = pd.DataFrame({
    'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',
                'Beans', 'Orange', 'Broccoli', 'Banana'],
    'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',
                 'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
    'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
    'Amount': [270, 239, 617, 384, 626, 610, 62, 90]
})

print(df)


    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90


In [25]:
print(df[['Product', 'Quantity']])

    Product  Quantity
0   Carrots         8
1  Broccoli         5
2    Banana         3
3    Banana         4
4     Beans         5
5    Orange         9
6  Broccoli        11
7    Banana         8


In [26]:
print(df.loc[[4, 6]])

    Product   Category  Quantity  Amount
4     Beans  Vegetable         5     626
6  Broccoli  Vegetable        11      62


In [27]:
print(df.groupby('Product')['Quantity'].sum())

Product
Banana      15
Beans        5
Broccoli    16
Carrots      8
Orange       9
Name: Quantity, dtype: int64


In [28]:
print(df.groupby('Category')['Amount'].sum())

Category
Fruit        1701
Vegetable    1197
Name: Amount, dtype: int64
